#!/bin/bash
set -euo pipefail
# Passwords generated by lab.py contain only letters and digits.
[[ "$APP_DB_PASSWORD" =~ ^[A-Za-z0-9]{20,64}$ ]] || { echo 'Invalid APP password format'; exit 1; }
sqlplus -s / as sysdba <<SQL
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;
CREATE USER APP IDENTIFIED BY "$APP_DB_PASSWORD" DEFAULT TABLESPACE USERS QUOTA 100M ON USERS;
GRANT CREATE SESSION, CREATE TABLE TO APP;
EXIT;
SQL
touch /opt/oracle/oradata/.delivery-lab-ready
