#!/bin/bash
set -euo pipefail
# Passwords generated by lab.py contain only letters and digits.
[[ "$APP_DB_PASSWORD" =~ ^[A-Za-z0-9]{20,64}$ ]] || { echo 'Invalid APP password format'; exit 1; }
sqlplus -L -s / as sysdba <<SQL
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT FAILURE
ALTER SESSION SET CONTAINER = FREEPDB1;
DECLARE
    existing_count NUMBER;
BEGIN
    -- Do not assume the Lite image provides a USERS tablespace.
    SELECT COUNT(*) INTO existing_count FROM dba_tablespaces WHERE tablespace_name = 'APP_DATA';
    IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE APP_DATA DATAFILE ''/opt/oracle/oradata/delivery-lab-app.dbf'' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE 100M';
    END IF;
    SELECT COUNT(*) INTO existing_count FROM dba_users WHERE username = 'APP';
    IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APP IDENTIFIED BY "$APP_DB_PASSWORD" DEFAULT TABLESPACE APP_DATA QUOTA 100M ON APP_DATA';
    END IF;
END;
/
-- Repeated deployments preserve the existing user, password, and tables.
ALTER USER APP DEFAULT TABLESPACE APP_DATA QUOTA 100M ON APP_DATA;
-- Identity columns create an underlying sequence in APP's own schema.
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO APP;
EXIT SUCCESS;
SQL
